FROM postgres:latest
#ADD docker-entrypoint-initdb.d/* /docker-entrypoint-initdb.d/
ADD docker-entrypoint-initdb.d/creat.user.sql /docker-entrypoint-initdb.d/
ADD docker-entrypoint-initdb.d/schema.base.sql /docker-entrypoint-initdb.d/
