version: "2"
services:
  postgres:
    restart: always
    build: postgres
    volumes:
      - /var/lib/postgresql
    expose:
      - "5432"

  web:
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - postgres:postgres
    env_file:
      ./settings.env
