version: "2"
services:
  postgres:
    restart: always
    build: api/postgres
    volumes:
      - /var/lib/postgresql
    expose:
      - "5432"

  server:
    restart: always
    build: api
    ports:
      - "8080:5000"
    links:
      - postgres:postgres
    env_file:
      ./api/settings.env

  web:
    restart: always
    build: client
    ports:
      - "80:4000"
